hackathon/app/controllers/account_controller.py
from flask import Blueprint, jsonify, request, flash, render_template
from app.models.account import Account
from app.controllers.authentication_controller import login_required
from app import db
from sqlalchemy import exc

# Create a blueprint for account-related routes
account_bp = Blueprint("account", __name__)

@account_bp.route("/")
@login_required
def list_accounts():
    accounts = Account.query.all()
    return jsonify([{"name": a.name, "username": a.username, "hall": a.hall} for a in accounts])

@account_bp.route("/<int:id>")
@login_required
def account_details(id):
    account = Account.query.get(id)
    return jsonify({"name": account.name, "email": account.email})

@account_bp.route('/loyalty')
@login_required
def loyalty():
    return render_template('account/loyal.html')

def add_points(account:Account):
    account.points += 5
    check_status(account)

def check_status(account:Account):
    # Update status based on points
    if account.points >= 400:
        account.status = 'Free Wash And Dry!'
    elif account.points >= 200:
        account.status = 'Free Wash Or Dry!'
    elif account.points >= 100:
        account.status = '50 Percent Off Next Wash Or Dry!'
    elif account.points >= 50:
        account.status = '20 Percent Off Next Wash Or Dry!'
    else:
        account.status = 'No Discount Yet'
    
    db.session.commit()

def redeem_points(account:Account, reward):
    # Redeem points for rewards
    if account.points >= reward['points']:
        account.points -= reward['points']
        account.rewards.append(reward)
        account.check_status()  # Update status after redeeming
        flash(f"{account.name} redeemed {reward['name']} for {reward['points']} points.")
        return True
    flash(f"{account.name} does not have enough points to redeem {reward['name']}.")
    return False

hackathon/app/controllers/homepage_controller.py
from flask import Blueprint, flash, render_template, request, url_for

from app.controllers.authentication_controller import login_required
from app.controllers.appointment_controller import list_appointments
from app import db

# Create a blueprint for account-related routes
homepage_bp = Blueprint("homepage", __name__)

@homepage_bp.route("/")
@login_required
def index():
    return render_template("schedule.html", appointments=list_appointments())

hackathon/app/controllers/notice_controller.py
from flask import (
    Blueprint, flash, redirect, render_template, request, session, url_for, g
)
from sqlalchemy import exc
from app.models.notice import Notice
from app.controllers.authentication_controller import login_required
from app import db

notice_bp = Blueprint("notice", __name__)

@notice_bp.route("/", methods=("GET",))
@login_required
def list_notices():
    notices = Notice.query.all()
    return render_template("notice/noticeboard.html", notices=notices)

@notice_bp.route("/create", methods=("GET", "POST"))
@login_required
def create_notice():
    if request.method == "POST":
        _title = request.form.get('title')
        _content = request.form.get('content')
        error = None

        if not _title or not _content:
            error = "All fields are required."
        
        if error is None:
            new_notice = Notice(
                title=_title,
                content=_content
            )
            db.session.add(new_notice)
            db.session.commit()
            return redirect(url_for("index"))
        
        flash(error)
        
    return render_template("notice/create.html")

@notice_bp.route("/<int:id>/edit", methods=("GET", "POST"))
@login_required
def edit_notice(id):
    notice = Notice.query.get(id)
    if not g.user.is_admin:
        flash("You are not authorized to edit this notice.")
        return redirect(url_for("index"))

    if request.method == "POST":
        _title = request.form.get('title')
        _content = request.form.get('content')
        error = None

        if not _title or not _content:
            error = "All fields are required."

        if error is None:
            notice.title = _title
            notice.content = _content
            db.session.commit()
            flash("Notice updated successfully!")
            return redirect(url_for("index"))

        flash(error)

    return render_template("notice/edit.html", notice=notice)

@notice_bp.route("/<int:id>/delete", methods=("POST",))
@login_required
def delete_notice(id):
    notice = Notice.query.get(id)
    if not g.user.is_admin:
        flash("You are not authorized to delete this notice.")
        return redirect(url_for("index"))

    db.session.delete(notice)
    db.session.commit()
    flash("Notice deleted successfully!")
    return redirect(url_for("index"))

hackathon/app/controllers/report_controller.py
from flask import (
    Blueprint, flash, redirect, render_template, request, session, url_for, g
)
from sqlalchemy import exc
from app.models.report import Report
from app.controllers.authentication_controller import login_required
from app import db

report_bp = Blueprint("report", __name__)

@report_bp.route("/", methods=["GET"])
@login_required
def list_reports():
    if g.user.is_admin:
        reports = Report.query.all()
    else:
        reports = Report.query.filter_by(account_id=session.get("user_id")).all()
    return render_template("report/reports.html", reports=reports)

@report_bp.route("/create", methods=("GET", "POST"))
@login_required
def create_report():
    if request.method == "POST":
        _title = request.form.get('issue')
        _content = request.form.get('message')
        error = None

        if not _title or not _content:
            error = "All fields are required."
        
        if error is None:
            new_report = Report(
                title=_title,
                content=_content,
                account_id=session.get('user_id'),
                account=g.user
            )
            db.session.add(new_report)
            db.session.commit()
            return redirect(url_for("index"))
        
        flash(error)
        
    return render_template("report/create.html")

@report_bp.route("/<int:id>/edit", methods=("GET", "POST"))
@login_required
def edit_report(id):
    report = Report.query.get(id)
    if not g.user.is_admin:
        flash("You are not authorized to edit this report.")
        return redirect(url_for("index"))

    if request.method == "POST":
        _title = request.form.get('issue')
        _content = request.form.get('message')
        error = None

        if not _title or not _content:
            error = "All fields are required."

        if error is None:
            report.title = _title
            report.content = _content
            db.session.commit()
            flash("Report updated successfully!")
            return redirect(url_for("index"))

        flash(error)

    return render_template("report/edit.html", report=report)

@report_bp.route("/<int:id>/delete", methods=("POST",))
@login_required
def delete_report(id):
    report = Report.query.get(id)
    if not g.user.is_admin:
        flash("You are not authorized to delete this report.")
        return redirect(url_for("index"))

    db.session.delete(report)
    db.session.commit()
    flash("Report deleted successfully!")
    return redirect(url_for("index"))

hackathon/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mental Health Matters {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">

    <!-- CSS Links -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a id="navbar-brand" href="{{ url_for('homepage.index') }}"><i class="fa-regular fa-heart"></i></i> Mental Health Matters </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    {% if g.user %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('index')}}">Appointment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('notice.list_notices')}}"> Notices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('report.list_reports')}}">{{'My ' if not g.user.is_admin else ''}}Reports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{url_for('account.loyalty')}}"> Loyalty Points</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id='logout-nav' href="{{ url_for('auth.logout') }}" onclick="return confirm('You will be logged out!');">Log Out</a>
                        </li>
                        
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="content">
        <!-- Header -->
        <header>
            {% block header %}{% endblock %}
        </header>

        <!-- Main Content -->
        <div class="container mt-5">
            {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
            {% endfor %}
            
            {% block content %}
            <!-- Child templates will override this block -->
            {% endblock %}
        </div>
    </div>

    <!-- Footer -->
    <footer class="bg-light text-center py-3 mt-4">
        <div class="container">
            <span class="text-muted">2025 Hackathon ... Mental Health Matters</span>
        </div>
    </footer>

    <!-- JavaScript Links -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>
</html>

hackathon/app/templates/schedule.html
{% extends 'layout.html' %}

{% block title %}Schedule{% endblock %}

{% block header %}
    <h1 class="text-center"><i class="fa-solid fa-pen-nib fa-lg" style="color: #2c58ce;"></i> Appointments Schedule</h1>
{% endblock %}

{% block content %}
    <table class="table table-bordered mt-4">
        <thead class="table-dark">
            <tr id="appointment-row">
                <th><i class="fa-solid fa-users" style="color: #ffffff;"></i></th>
                <th>Name</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Cognitive Behavioral Therapy (CBT)</th>
                <th>Dialectical Behavior Therapy (DBT)</th>
                <th>Completed</th>
                <th>Remaining Time</th>
                <th><i class="fa-solid fa-pen" style="color: #ffffff;"></i></th>
            </tr>
        </thead>
        <tbody>
            {% for appointment in appointments %}
            <tr id="appointment-row-else">
                <td>{{ loop.index }}</td>
                <td>{{ appointment.account.name }}</td>
                <td>{{ appointment.start_time.strftime('%I:%M %p') }}</td>
                <td>{{ appointment.end_time.strftime('%I:%M %p') }}</td>
                <td>{{ appointment.washes }}</td>
                <td>{{ appointment.dries }}</td>
                <td>{{ 'Yes' if appointment.completed else 'No' }}</td>
                <td>
                    <span 
                        class="remaining-time"
                        data-end-time="{{ appointment.end_time.strftime('%Y-%m-%dT%H:%M:%S') }}"
                        data-start-time="{{ appointment.start_time.strftime('%Y-%m-%dT%H:%M:%S') }}">
                    </span>
                </td>
                <td>
                    {% if session.get('user_id') == appointment.account_id %}
                    <a href="{{ url_for('appointment.edit_appointment', id=appointment.id) }}" class="btn btn-warning btn-sm" style="display:inline-block; margin: 5%;">Edit</a> 
                    <form onsubmit="return confirm('Your appointment will be deleted!');" action="{{ url_for('appointment.delete_appointment', id=appointment.id) }}" method="POST" style="display:inline-block;">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>        
    </table>
    <a href="{{ url_for('appointment.create_appointment') }}" class="btn btn-primary mt-3">Create New Appointment</a> 

    <div id="confirmationModal">
        <div class="modal-content">
            <h4 class="text-center">Session Completed</h4>
            <p class="text-center">Continue</p>
            <div class="modal-buttons">
                <button id="modalConfirm" class="btn btn-success">Yes</button>
            </div>
        </div>
    </div>
    
{% endblock %}